spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  pathsTOMatch: /api/**/v1/**
  swagger-ui:
    user-root-path: true